Pre-release r1.1 of v0.1.0-rc.1
camaraproject/LocationInsights pull request #18
Opened 2024-11-26 12:14 UTC by fernandopradocabrillo

#### What type of PR is this?

Add one of the following kinds:
* subproject management

#### What this PR does / why we need it:
Include neccesary documentation to create the first public pre-release r1.1

#### Which issue(s) this PR fixes:

Fixes #17 
Fixes #19

2024-11-26 13:16 UTC, FabrizioMoggio submitted a review, later dismissed

2024-11-26 19:02 UTC, hdamker commented
@FabrizioMoggio Thanks, I will create the review issue within Release Management. 

And: I know it is confusing, but it is either a pre-release (if the the API version is an alpha or rc version) or a release of a public API version ... there is no such thing as a public pre-release. I edited the title of the PR accordingly.

2024-12-10 15:14 UTC, hdamker requested changes
Looks generally good from Release Management point of view, but the links within CHANGELOG need to be corrected.

2024-12-10 15:14 UTC, hdamker commented on CHANGELOG.md
> +* @wrathwolf made their first contribution in https://github.com/camaraproject/LocationInsights/pull/2
These two lines should be removed (the PRs are for good reason not listed above).
```suggestion
```

2024-12-10 15:14 UTC, hdamker commented on CHANGELOG.md
> +  - [View it on Swagger Editor](https://editor.swagger.io/?url=https://raw.githubusercontent.com/camaraproject/LocationInsights/blob/r1.1/code/API_definitions/most-frequent-location.yaml)
These links wouldn't work, correction (compare with README.md):

```suggestion
  - [View it on ReDoc](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/camaraproject/LocationInsights/r1.1/code/API_definitions/most-frequent-location.yaml&nocors)
  - [View it on Swagger Editor](https://editor.swagger.io/?url=https://raw.githubusercontent.com/camaraproject/LocationInsights/r1.1/code/API_definitions/most-frequent-location.yaml)
```

Hint: you can test the links by temporarily creating a branch `r1.1` (you would need to delete it before creating the release tag).

2024-12-10 15:23 UTC, hdamker commented
A question about the version and the aim for Spring25: The [release tracker for 0.1.0](https://lf-camaraproject.atlassian.net/wiki/spaces/CAM/pages/45056012/most-frequent-location+v0.1.0) is stating that the version 0.1.0 is targeted for Spring25 meta-release. For that meta-release the API should be based on Commonalities 0.5.0 (e.g. some changes to error schema) and you will have the public release around March 2025.

There two options which come to my mind (there might be others):
* doing now soon a public release of 0.1.0 outside of meta-release cycle and doing the adaptions for Spring25 in a 0.2.0
* releasing now an alpha version of 0.1.0 and doing the adaptions to Commonalities 0.5.0 until the release candidate

@fernandopradocabrillo Would be great to share your plan towards the Spring25 meta-release.

2024-12-10 15:41 UTC, fernandopradocabrillo commented
> A question about the version and the aim for Spring25: The [release tracker for 0.1.0](https://lf-camaraproject.atlassian.net/wiki/spaces/CAM/pages/45056012/most-frequent-location+v0.1.0) is stating that the version 0.1.0 is targeted for Spring25 meta-release. For that meta-release the API should be based on Commonalities 0.5.0 (e.g. some changes to error schema) and you will have the public release around March 2025.
> 
> There two options which come to my mind (there might be others):
> 
> * doing now soon a public release of 0.1.0 outside of meta-release cycle and doing the adaptions for Spring25 in a 0.2.0
> * releasing now an alpha version of 0.1.0 and doing the adaptions to Commonalities 0.5.0 until the release candidate
> 
> @fernandopradocabrillo Would be great to share your plan towards the Spring25 meta-release.

Hi @hdamker, you are right, I have to update the release tracker to v0.2.0.

The idea is to publish a first version aligned with Fall24 and the update the spec and align with Spring25 for a v0.2.0. At least in TEF we need an oficial version align with current agreements before going for the new one. I though I could have it before, but the WG is a bit short-staffed so it takes time 😄 

Thanks for pointing it out, I'll update the release tracker and proceed with the updates once I have the release created here. If possible, before the M3 due date.

2024-12-10 15:55 UTC, hdamker commented
> I'll update the release tracker and proceed with the updates once I have the release created here. If possible, before the M3 due date.

Please keep the release tracker for 0.1.0, we are tracking them also [here](https://lf-camaraproject.atlassian.net/wiki/spaces/CAM/pages/36012257/Sandbox+APIs+APIs+not+yet+in+any+meta-release). I've updated the release tracker accordingly.  For 0.2.0 please create an additional release tracker.

2024-12-10 15:59 UTC, hdamker approved these changes
LGTM - you are good to go as soon as there is a approval for the latest change from a @camaraproject/location-insights_codeowners

2024-12-11 08:50 UTC, FabrizioMoggio approved these changes
LGTM :-)

2024-12-11 09:38 UTC, merged