Update README.md
camaraproject/LocationInsights pull request #2
Opened 2024-05-16 14:06 UTC by wrathwolf

Update wiki and mailing list info

2024-05-16 19:23 UTC, hdamker requested changes

2024-05-16 19:23 UTC, hdamker commented on README.md
> +    * A message to the community of this Sub Project can be sent using <sp-locationinsights@lists.camaraproject.org>.
I would propose to follow the same syntax as for the GitHub teams and other mailing lists and transform the CamelCase "LocationInsigts" to kebab-case "location-insights" within the mailing list (as originally proposed).

2024-05-16 19:23 UTC, hdamker commented on README.md
>      * (NOTE: mailing list need still to be created - thanks for your patience)
This line need to be deleted.

2024-05-21 13:05 UTC, hdamker approved these changes
Mailing list is now as planned sp-location-insights@lists.camaraproject.org

2024-05-21 13:12 UTC, hdamker commented
@camaraproject/location-insights_codeowners @camaraproject/location-insights_maintainers:
The mailing list https://lists.camaraproject.org/g/sp-location-insights is now available.

Please 
a) subscribe to the mailing list
b) approve and merge the PR

2024-06-13 07:15 UTC, hdamker commented
@camaraproject/location-insights_codeowners can one of the Codeowners please approve this PR so that it can be merged? The last change was done three weeks ago ...

2024-06-13 09:22 UTC, chinaunicomyangfan approved these changes
LGTM

2024-06-13 09:34 UTC, merged